/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_andresmoncada;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Dell
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f_usuarios = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_u = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jd_nu = new javax.swing.JDialog();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nom = new javax.swing.JTextField();
        tf_edad = new javax.swing.JTextField();
        tf_user = new javax.swing.JTextField();
        tf_pass = new javax.swing.JPasswordField();
        f_canc = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_a = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_c = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jd_nc = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_cnom = new javax.swing.JTextField();
        tf_cgen = new javax.swing.JTextField();
        tf_dur = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        f_alb = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_alb = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_alb = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        label_albnom = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jd_na = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_anom = new javax.swing.JTextField();
        tf_aart = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jd_signin = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_siu = new javax.swing.JTextField();
        tf_sipass = new javax.swing.JPasswordField();
        jButton12 = new javax.swing.JButton();
        f_si = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_exp = new javax.swing.JMenuItem();
        jmi_cp = new javax.swing.JMenuItem();
        jmi_pl = new javax.swing.JMenuItem();
        jmi_fav = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenuItem();
        f_exp = new javax.swing.JFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_expa = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_expc = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jd_pl = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        jl_ps = new javax.swing.JList<>();
        jButton15 = new javax.swing.JButton();
        jd_verpl = new javax.swing.JDialog();
        jScrollPane9 = new javax.swing.JScrollPane();
        jt_pl = new javax.swing.JTree();
        f_fav = new javax.swing.JFrame();
        jScrollPane10 = new javax.swing.JScrollPane();
        jt_fav = new javax.swing.JTree();
        jButton16 = new javax.swing.JButton();
        jpm_tree = new javax.swing.JPopupMenu();
        jmi_cdel = new javax.swing.JMenuItem();
        cb_menu = new javax.swing.JComboBox<>();
        boton_in = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        f_usuarios.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                f_usuariosWindowClosing(evt);
            }
        });

        jl_u.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_u);

        jLabel2.setText("Usuarios");

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout f_usuariosLayout = new javax.swing.GroupLayout(f_usuarios.getContentPane());
        f_usuarios.getContentPane().setLayout(f_usuariosLayout);
        f_usuariosLayout.setHorizontalGroup(
            f_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_usuariosLayout.createSequentialGroup()
                .addGroup(f_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(f_usuariosLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(f_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(f_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(f_usuariosLayout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(f_usuariosLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton4)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        f_usuariosLayout.setVerticalGroup(
            f_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f_usuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(f_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Username");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Edad");

        javax.swing.GroupLayout jd_nuLayout = new javax.swing.GroupLayout(jd_nu.getContentPane());
        jd_nu.getContentPane().setLayout(jd_nuLayout);
        jd_nuLayout.setHorizontalGroup(
            jd_nuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuLayout.createSequentialGroup()
                .addGroup(jd_nuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_nuLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel3))
                    .addGroup(jd_nuLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel6))
                    .addGroup(jd_nuLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jd_nuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_edad)
                            .addComponent(tf_nom)
                            .addComponent(tf_user, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(tf_pass)))
                    .addGroup(jd_nuLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel4))
                    .addGroup(jd_nuLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel5))
                    .addGroup(jd_nuLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton3)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jd_nuLayout.setVerticalGroup(
            jd_nuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        f_canc.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                f_cancWindowClosing(evt);
            }
        });

        jl_a.setModel(new DefaultListModel());
        jl_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_aMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_a);

        jl_c.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_c);

        jLabel7.setText("Canciones");

        jLabel8.setText("Albumes");

        jButton5.setText("Agregar Canción");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Regresar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout f_cancLayout = new javax.swing.GroupLayout(f_canc.getContentPane());
        f_canc.getContentPane().setLayout(f_cancLayout);
        f_cancLayout.setHorizontalGroup(
            f_cancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_cancLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(f_cancLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f_cancLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(140, 140, 140)
                .addComponent(jButton7)
                .addContainerGap())
        );
        f_cancLayout.setVerticalGroup(
            f_cancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_cancLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f_cancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(f_cancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(f_cancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Nombre");

        jLabel10.setText("Género");

        jLabel11.setText("Duración (s)");

        jButton6.setText("Agregar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ncLayout = new javax.swing.GroupLayout(jd_nc.getContentPane());
        jd_nc.getContentPane().setLayout(jd_ncLayout);
        jd_ncLayout.setHorizontalGroup(
            jd_ncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ncLayout.createSequentialGroup()
                .addGroup(jd_ncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ncLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jd_ncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_cnom, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(tf_cgen)))
                    .addGroup(jd_ncLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(jd_ncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_dur)))
                    .addGroup(jd_ncLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ncLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel9))
                    .addGroup(jd_ncLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel10)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jd_ncLayout.setVerticalGroup(
            jd_ncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_cnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(tf_cgen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(tf_dur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(19, 19, 19))
        );

        f_alb.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                f_albWindowClosing(evt);
            }
        });

        jl_alb.setModel(new DefaultListModel());
        jl_alb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_albMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jl_alb);

        jt_alb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Artista", "Género", "Duración"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jt_alb);

        jLabel12.setText("Albumes");

        jButton8.setText("Agregar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Eliminar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Regresar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout f_albLayout = new javax.swing.GroupLayout(f_alb.getContentPane());
        f_alb.getContentPane().setLayout(f_albLayout);
        f_albLayout.setHorizontalGroup(
            f_albLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f_albLayout.createSequentialGroup()
                .addGroup(f_albLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(f_albLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel12))
                    .addGroup(f_albLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(f_albLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(f_albLayout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton9))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(f_albLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(label_albnom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f_albLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addContainerGap())
        );
        f_albLayout.setVerticalGroup(
            f_albLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_albLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(f_albLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(label_albnom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(f_albLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(f_albLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel13.setText("Nombre");

        jLabel14.setText("Artista");

        jButton11.setText("Agregar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_naLayout = new javax.swing.GroupLayout(jd_na.getContentPane());
        jd_na.getContentPane().setLayout(jd_naLayout);
        jd_naLayout.setHorizontalGroup(
            jd_naLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_naLayout.createSequentialGroup()
                .addGroup(jd_naLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_naLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_naLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(tf_anom, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                        .addGroup(jd_naLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(tf_aart)))
                    .addGroup(jd_naLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel14))
                    .addGroup(jd_naLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel13))
                    .addGroup(jd_naLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_naLayout.setVerticalGroup(
            jd_naLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_naLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(10, 10, 10)
                .addComponent(tf_anom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(tf_aart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addContainerGap())
        );

        jLabel15.setText("Username");

        jLabel16.setText("Contraseña");

        jButton12.setText("Iniciar sessión");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_signinLayout = new javax.swing.GroupLayout(jd_signin.getContentPane());
        jd_signin.getContentPane().setLayout(jd_signinLayout);
        jd_signinLayout.setHorizontalGroup(
            jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signinLayout.createSequentialGroup()
                .addGroup(jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signinLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel15))
                    .addGroup(jd_signinLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel16))
                    .addGroup(jd_signinLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_siu, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(tf_sipass)))
                    .addGroup(jd_signinLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton12)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jd_signinLayout.setVerticalGroup(
            jd_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_siu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_sipass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        f_si.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                f_siWindowClosing(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel19.setText("Hola");

        jMenu1.setText("Acciones");

        jmi_exp.setText("Explorar");
        jmi_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_expActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_exp);

        jmi_cp.setText("Crear Playlists");
        jmi_cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cpActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_cp);

        jmi_pl.setText("Ver Playlists");
        jmi_pl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_plActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_pl);

        jmi_fav.setText("Ver Favoritos");
        jmi_fav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_favActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_fav);

        jmi_salir.setText("Salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_salir);

        jMenuBar1.add(jMenu1);

        f_si.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout f_siLayout = new javax.swing.GroupLayout(f_si.getContentPane());
        f_si.getContentPane().setLayout(f_siLayout);
        f_siLayout.setHorizontalGroup(
            f_siLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_siLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel19)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        f_siLayout.setVerticalGroup(
            f_siLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_siLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel19)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        f_exp.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                f_expWindowClosing(evt);
            }
        });

        jl_expa.setModel(new DefaultListModel());
        jl_expa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_expaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jl_expa);

        jl_expc.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_expc);

        jLabel17.setText("Canciones");

        jLabel18.setText("Albumes");

        jButton13.setText("Agregar a Playlist");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Regresar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout f_expLayout = new javax.swing.GroupLayout(f_exp.getContentPane());
        f_exp.getContentPane().setLayout(f_expLayout);
        f_expLayout.setHorizontalGroup(
            f_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_expLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(f_expLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f_expLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(29, 29, 29)
                .addComponent(jButton14)
                .addContainerGap())
        );
        f_expLayout.setVerticalGroup(
            f_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_expLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(f_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addGroup(f_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jl_ps.setModel(new DefaultListModel()
        );
        jScrollPane8.setViewportView(jl_ps);

        jButton15.setText("Agregar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_plLayout = new javax.swing.GroupLayout(jd_pl.getContentPane());
        jd_pl.getContentPane().setLayout(jd_plLayout);
        jd_plLayout.setHorizontalGroup(
            jd_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_plLayout.createSequentialGroup()
                .addGroup(jd_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_plLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton15))
                    .addGroup(jd_plLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_plLayout.setVerticalGroup(
            jd_plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_plLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addContainerGap())
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Playlists");
        jt_pl.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_pl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_plMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jt_pl);

        javax.swing.GroupLayout jd_verplLayout = new javax.swing.GroupLayout(jd_verpl.getContentPane());
        jd_verpl.getContentPane().setLayout(jd_verplLayout);
        jd_verplLayout.setHorizontalGroup(
            jd_verplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_verplLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_verplLayout.setVerticalGroup(
            jd_verplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_verplLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Favoritos");
        jt_fav.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane10.setViewportView(jt_fav);

        jButton16.setText("Reproducir");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout f_favLayout = new javax.swing.GroupLayout(f_fav.getContentPane());
        f_fav.getContentPane().setLayout(f_favLayout);
        f_favLayout.setHorizontalGroup(
            f_favLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_favLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        f_favLayout.setVerticalGroup(
            f_favLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_favLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f_favLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton16)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jmi_cdel.setText("jMenuItem1");
        jmi_cdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cdelActionPerformed(evt);
            }
        });
        jpm_tree.add(jmi_cdel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuarios", "Canciones", "Albums", "Log In", "Guardar Usuarios", "Cargar Usuarios" }));

        boton_in.setText("Ingresar");
        boton_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_inActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Funciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(boton_in)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_inActionPerformed
        int op = cb_menu.getSelectedIndex();
        switch(op){
            case 0://usuarios
                DefaultListModel lm = new DefaultListModel();
                for (Usuario usuario : usuarios) {
                    lm.addElement(usuario);
                }
                this.setVisible(false);
                jl_u.setModel(lm);
                f_usuarios.pack();
                f_usuarios.setLocationRelativeTo(this);
                f_usuarios.setVisible(true);
                break;
            case 1://Canciones
                lm = new DefaultListModel();
                for (Album a : albums) {
                    lm.addElement(a);
                }
                this.setVisible(false);
                jl_a.setModel(lm);
                f_canc.pack();
                f_canc.setLocationRelativeTo(this);
                f_canc.setVisible(true);
                break;
            case 2://Albums
                lm = new DefaultListModel();
                for (Album a : albums) {
                    lm.addElement(a);
                }
                this.setVisible(false);
                jl_alb.setModel(lm);
                f_alb.pack();
                f_alb.setLocationRelativeTo(this);
                f_alb.setVisible(true);
                break;
            case 3://Sign in
                jd_signin.setModal(true);
                jd_signin.pack();
                jd_signin.setLocationRelativeTo(this);
                jd_signin.setVisible(true);
                break;
            case 4://Guardar usuarios
                guardar();
                break;
            case 5://Cargar usuarios
                cargar();
        }
    }//GEN-LAST:event_boton_inActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            DefaultListModel lm = (DefaultListModel) jl_u.getModel();
            Usuario u = new Usuario(tf_nom.getText(),Integer.parseInt(tf_edad.getText()),tf_user.getText(),tf_pass.getText());
            lm.addElement(u);
            usuarios.add(u);
            jl_u.setModel(lm);
            jd_nu.setVisible(false);
            tf_nom.setText("");
            tf_edad.setText("");
            tf_user.setText("");
            tf_pass.setText("");
        }catch (Exception e){
            JOptionPane.showMessageDialog(f_usuarios, "Se prodijo un error al agregar el usuario", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jd_nu.setModal(true);
        jd_nu.pack();
        jd_nu.setLocationRelativeTo(f_usuarios);
        jd_nu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jl_u.getSelectedIndex() >= 0){
            DefaultListModel lm = (DefaultListModel) jl_u.getModel();
            lm.remove(jl_u.getSelectedIndex());
            usuarios.remove(jl_u.getSelectedIndex());
            jl_u.setModel(lm);
        }else
            JOptionPane.showMessageDialog(f_usuarios, "Seleccione un usuario en la lista primero", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        f_usuarios.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void f_usuariosWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_f_usuariosWindowClosing
        setVisible(true);
    }//GEN-LAST:event_f_usuariosWindowClosing

    private void jl_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_aMouseClicked
        if(jl_a.getSelectedIndex() >= 0){
            DefaultListModel lm = (DefaultListModel) jl_a.getModel();
            atemp = (Album)lm.getElementAt(jl_a.getSelectedIndex());
            DefaultListModel lmc = new DefaultListModel();
            for (Cancion c : atemp.getCanciones()) {
                lmc.addElement(c);
            }
            jl_c.setModel(lmc);
        }
    }//GEN-LAST:event_jl_aMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jl_a.getSelectedIndex() >= 0){
            jd_nc.setModal(true);
            jd_nc.pack();
            jd_nc.setLocationRelativeTo(f_canc);
            jd_nc.setVisible(true);
        }else if(((DefaultListModel)jl_a.getModel()).getSize() == 0){
            JOptionPane.showMessageDialog(f_usuarios, "Se neceita tener albumes para agregar canciones", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else
            JOptionPane.showMessageDialog(f_usuarios, "Seleccione un album en la lista primero", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Cancion c = new Cancion(tf_cnom.getText(),atemp.getArtista(),tf_cgen.getText(),Integer.parseInt(tf_dur.getText()));
            atemp.getCanciones().add(c);
            albums.set(jl_a.getSelectedIndex(), atemp);
            DefaultListModel lm = (DefaultListModel) jl_a.getModel();
            lm.setElementAt(atemp, jl_a.getSelectedIndex());
            tf_cnom.setText("");
            tf_cgen.setText("");
            tf_dur.setText("");
            jd_nc.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(f_usuarios, "Se prodijo un error al agregar la cancion", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void f_cancWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_f_cancWindowClosing
        setVisible(true);
    }//GEN-LAST:event_f_cancWindowClosing

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        f_canc.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jl_albMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_albMouseClicked
        if(jl_alb.getSelectedIndex() >= 0){
            DefaultListModel lm = (DefaultListModel) jl_alb.getModel();
            atemp = (Album)lm.getElementAt(jl_alb.getSelectedIndex());
            label_albnom.setText(atemp.getNombre());
            DefaultTableModel tm = (DefaultTableModel) jt_alb.getModel();
            for (Cancion c : atemp.getCanciones()) {
                tm.addRow(c.getRow());
            }
            jt_alb.setModel(tm);
        }
    }//GEN-LAST:event_jl_albMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jd_na.setModal(true);
        jd_na.pack();
        jd_na.setLocationRelativeTo(f_canc);
        jd_na.setVisible(true);        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void f_albWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_f_albWindowClosing
        setVisible(true);
    }//GEN-LAST:event_f_albWindowClosing

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        f_alb.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        atemp = new Album(tf_anom.getText(),tf_aart.getText());
        albums.add(atemp);
        DefaultListModel lm = (DefaultListModel) jl_alb.getModel();
        lm.addElement(atemp);
        jl_alb.setModel(lm);
        tf_anom.setText("");
        tf_aart.setText("");
        jd_na.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(jl_alb.getSelectedIndex() >= 0){
            DefaultListModel lm = (DefaultListModel) jl_alb.getModel();
            lm.remove(jl_alb.getSelectedIndex());
            albums.remove(jl_alb.getSelectedIndex());
            jl_alb.setModel(lm);
        }else
            JOptionPane.showMessageDialog(f_usuarios, "Seleccione un album en la lista primero", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        boolean v = false;
        for (Usuario u : usuarios) {
            if(u.getUser().equals(tf_siu.getText()) && u.getPass().equals(tf_sipass.getText())){
                v = true;
                utemp = u;
                break;
            }
        }
        if(v){
            jd_signin.setVisible(false);
            setVisible(false);
            tf_siu.setText("");
            tf_sipass.setText("");
            f_si.pack();
            f_si.setLocationRelativeTo(this);
            f_si.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(jd_signin, "Usuario o contraseña incorrectos");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        f_si.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_jmi_salirActionPerformed

    private void jmi_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_expActionPerformed
        f_si.setVisible(false);
        DefaultListModel lm = new DefaultListModel();
        for (Album a : albums) {
            lm.addElement(a);
        }this.setVisible(false);
        jl_expa.setModel(lm);
        f_exp.pack();
        f_exp.setLocationRelativeTo(this);
        f_exp.setVisible(true);
    }//GEN-LAST:event_jmi_expActionPerformed

    private void jl_expaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_expaMouseClicked
        if(jl_expa.getSelectedIndex() >= 0){
            DefaultListModel lm = (DefaultListModel) jl_expa.getModel();
            atemp = (Album)lm.getElementAt(jl_expa.getSelectedIndex());
            DefaultListModel lmc = new DefaultListModel();
            for (Cancion c : atemp.getCanciones()) {
                lmc.addElement(c);
            }
            jl_expc.setModel(lmc);
        }
    }//GEN-LAST:event_jl_expaMouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(jl_expc.getSelectedIndex() >= 0){
            DefaultListModel lm = new DefaultListModel();
            lm.addElement(utemp.getFavoritos());
            for (PlayList playlist : utemp.getPlaylists()) {
                lm.addElement(playlist);
            }
            jl_ps.setModel(lm);
            jd_pl.setModal(true);
            jd_pl.pack();
            jd_pl.setLocationRelativeTo(this);
            jd_pl.setVisible(true);
        }else
            JOptionPane.showMessageDialog(f_usuarios, "Escoja una canción primero", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        f_exp.setVisible(false);
        f_si.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed
    
    private void f_expWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_f_expWindowClosing
        f_si.setVisible(true);
    }//GEN-LAST:event_f_expWindowClosing

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        DefaultListModel lm = (DefaultListModel) jl_expc.getModel();
        DefaultListModel lmp = (DefaultListModel) jl_ps.getModel();
        if(jl_ps.getSelectedIndex() == 0){
            utemp.getFavoritos().getCanciones().add((Cancion)lm.getElementAt(jl_expc.getSelectedIndex()));
            jd_pl.setVisible(false);
        }else if(jl_ps.getSelectedIndex() > 0){
            utemp.getPlaylists().get(jl_ps.getSelectedIndex() - 1).getCanciones().add((Cancion)lm.getElementAt(jl_expc.getSelectedIndex()));
            jd_pl.setVisible(false);
        }else
            JOptionPane.showMessageDialog(f_usuarios, "Escoja playlist primero", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void f_siWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_f_siWindowClosing
        setVisible(true);
    }//GEN-LAST:event_f_siWindowClosing

    private void jmi_plActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_plActionPerformed
        DefaultTreeModel tm = (DefaultTreeModel)jt_pl.getModel();
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Playlists");
        DefaultMutableTreeNode np;
        DefaultMutableTreeNode nc;
        for (PlayList p : utemp.getPlaylists()) {
            np = new DefaultMutableTreeNode(p.getNombre());
            for (Cancion c : p.getCanciones()) {
                nc = new DefaultMutableTreeNode(c);
                np.add(nc);
            }
            raiz.add(np);
        }
        tm.setRoot(raiz);
        tm.reload();
        jd_verpl.setModal(true);
        jd_verpl.pack();
        jd_verpl.setLocationRelativeTo(f_si);
        jd_verpl.setVisible(true);
    }//GEN-LAST:event_jmi_plActionPerformed

    private void jmi_cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cpActionPerformed
        String nombre = JOptionPane.showInputDialog(f_si, "Nombre de la playlist:");
        utemp.getPlaylists().add(new PlayList(nombre));
    }//GEN-LAST:event_jmi_cpActionPerformed

    private void jmi_favActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_favActionPerformed
        DefaultTreeModel tm = (DefaultTreeModel)jt_fav.getModel();
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Favoritos");
        DefaultMutableTreeNode nc = new DefaultMutableTreeNode();
        for (Cancion c : utemp.getFavoritos().getCanciones()) {
            nc = new DefaultMutableTreeNode(c);
            raiz.add(nc);
        }
        raiz.add(nc);
        tm.setRoot(raiz);
        tm.reload();
        f_exp.setVisible(false);
        f_fav.pack();
        f_fav.setLocationRelativeTo(f_exp);
        f_fav.setVisible(true);
    }//GEN-LAST:event_jmi_favActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        DefaultTreeModel tm = (DefaultTreeModel)jt_fav.getModel();
        if(jt_fav.getSelectionCount() > 0){
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode)jt_fav.getSelectionPath().getLastPathComponent();
            if(nodo.getUserObject() instanceof Cancion){
                System.out.println("play");
                Cancion c = (Cancion)nodo.getUserObject();
                Play reproductor = new Play(f_fav,false,c);
                reproductor.setVisible(true);
                Thread t = new Thread(reproductor);
                t.start();
            }
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jt_plMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_plMouseClicked
        if(evt.isMetaDown()){
            int row = jt_pl.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_pl.setSelectionRow(row);
            jpm_tree.show(jt_pl, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jt_plMouseClicked

    private void jmi_cdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cdelActionPerformed
        DefaultTreeModel tm = (DefaultTreeModel)jt_pl.getModel();
        DefaultMutableTreeNode nodo = ((DefaultMutableTreeNode)jt_pl.getSelectionPath().getLastPathComponent());
        if(nodo.getUserObject() instanceof Cancion){
            Cancion c = (Cancion)nodo.getUserObject();
            String pl = ((String)((DefaultMutableTreeNode)nodo.getParent()).getUserObject());
            if (pl.equals("Favoritos")){
                utemp.getFavoritos().getCanciones().remove(c);
            }else{
                for (PlayList p : utemp.getPlaylists()) {
                    if(p.getNombre().equals(pl)){
                        p.getCanciones().remove(c);
                    }
                }
            }
            tm.removeNodeFromParent(nodo);
        }
        tm.reload();
    }//GEN-LAST:event_jmi_cdelActionPerformed
    
    private void cargar(){
        Admin a = new Admin("./usuarios.aml");
        a.cargarArchivo();
        usuarios = a.getUsuarios();
        JOptionPane.showMessageDialog(this, "Usuarios cargados");
    }

    private void guardar(){
        Admin a = new Admin("./usuarios.aml");
        for (Usuario u : usuarios) {
            if(!(a.getUsuarios().contains(u))){
                a.getUsuarios().add(u);
            }
        }
        a.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Usuarios guardados exitosamente");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JOptionPane.showMessageDialog(null, "Si una lista de canciones no se actualiza\n" + "hacer clic otra vez en su album");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_in;
    private javax.swing.JComboBox<String> cb_menu;
    private javax.swing.JFrame f_alb;
    private javax.swing.JFrame f_canc;
    private javax.swing.JFrame f_exp;
    private javax.swing.JFrame f_fav;
    private javax.swing.JFrame f_si;
    private javax.swing.JFrame f_usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JDialog jd_na;
    private javax.swing.JDialog jd_nc;
    private javax.swing.JDialog jd_nu;
    private javax.swing.JDialog jd_pl;
    private javax.swing.JDialog jd_signin;
    private javax.swing.JDialog jd_verpl;
    private javax.swing.JList<String> jl_a;
    private javax.swing.JList<String> jl_alb;
    private javax.swing.JList<String> jl_c;
    private javax.swing.JList<String> jl_expa;
    private javax.swing.JList<String> jl_expc;
    private javax.swing.JList<String> jl_ps;
    private javax.swing.JList<String> jl_u;
    private javax.swing.JMenuItem jmi_cdel;
    private javax.swing.JMenuItem jmi_cp;
    private javax.swing.JMenuItem jmi_exp;
    private javax.swing.JMenuItem jmi_fav;
    private javax.swing.JMenuItem jmi_pl;
    private javax.swing.JMenuItem jmi_salir;
    private javax.swing.JPopupMenu jpm_tree;
    private javax.swing.JTable jt_alb;
    private javax.swing.JTree jt_fav;
    private javax.swing.JTree jt_pl;
    private javax.swing.JLabel label_albnom;
    private javax.swing.JTextField tf_aart;
    private javax.swing.JTextField tf_anom;
    private javax.swing.JTextField tf_cgen;
    private javax.swing.JTextField tf_cnom;
    private javax.swing.JTextField tf_dur;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_nom;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JPasswordField tf_sipass;
    private javax.swing.JTextField tf_siu;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Usuario> usuarios = new ArrayList();
    private ArrayList<Album> albums = new ArrayList();
    private Album atemp;
    private Usuario utemp;
}
